### ISSUE TITLE
Website Domain

### ISSUE THREAD

**Issue by SeraphinaStephen** [SeraphinaStephen/tomato-root-architecture#10]
I've looked into a couple of website hosting options as considerations, these all seem pretty well reviewed so going forward I'll look into if that fit for what we need.

These where recommended as beginner friendly:  

https://www.a2hosting.com/web-hosting/?aid=5c9400b326496&cid=11111111&chan=code2

https://www.dreamhost.com/hosting/

These where recommended also and have a deal for cheaper hosting:  

https://www.nixihost.com/hosting/reddit

https://www.knownhost.com/reddit

_Originally posted by @SeraphinaStephen in https://github.com/SeraphinaStephen/tomato-root-architecture/issues/2#issuecomment-1937817574_

**Comment by JoannaBlatt** [comment]
It seems like the first one will work well for our needs and is cheap enough. We don't need much storage.

**Comment by SeraphinaStephen** [comment]
Starting draft on email for Dr.C
