### ISSUE TITLE
help page

### ISSUE THREAD

**Issue by JoannaBlatt** [SeraphinaStephen/tomato-root-architecture#11]
A FAQ/help page

**Comment by SeraphinaStephen** [comment]
I had to reacquaint myself with HTML and CSS but now I have the gist of it again and got what I needed started for the help page / about page also

**Comment by SeraphinaStephen** [comment]
I forgot to write this issue report but I pushed what changes I had made to the github so zekkie could continue work on their end.

**Comment by ZekkieMcCormick** [comment]
Coded, just need text now
