### ISSUE TITLE
Test automated pipeline

### ISSUE THREAD

**Issue by JoannaBlatt** [SeraphinaStephen/tomato-root-architecture#12]
Someone other than me (Joanna) needs to test the automated pipeline on their machine to make sure the output is the same. Afterwards we can build in fail safe and automated unit testing.

**Comment by JoannaBlatt** [comment]
run the big file and the small file then send the results to Dr. C. This involves for the big file doing `python write_architecture_files.py <filename>` then run automated pipeline. @SeraphinaStephen

**Comment by SeraphinaStephen** [comment]
Starting running the big file again since it wasn't able to finish before,

**Comment by SeraphinaStephen** [comment]
I think I'm having issues with running the big file since its taking much much longer then expected

**Comment by SeraphinaStephen** [comment]
I fixed the issue I was having that was preventing me from running the large file provided by Dr.C and I restarted the auto pipeline, unfortunately it looks like it won't finish before I have to leave for work today

**Comment by SeraphinaStephen** [comment]
I have to restart the data pipeline today again unfortunately, but because I have no work it will be able to run to completion

**Comment by SeraphinaStephen** [comment]
I talked with Joanna since I was having some issues with the data pipeline, and I got everything running smoothy again, and I understand how the data pipeline better.

**Comment by SeraphinaStephen** [comment]
I am still waiting on the arbors to process, it seems like it might take longer on my end then it did for Joanna, I'll have to figure out if its something else that I am doing wrong

**Comment by SeraphinaStephen** [comment]
the large file is taking too long to download so I am going to leave it for now and move on to work on the about page instead

**Comment by SeraphinaStephen** [comment]
I'm working on the about page and the help page now, I'm making sure that I'm working on the page correctly without stepping on any toes

**Comment by SeraphinaStephen** [comment]
I actually just got it to finish analyzing the big file and I just finished downloading it, and uploaded it into the google drive in the results folder
