### ISSUE TITLE
Session timer implementation

### ISSUE THREAD

**Issue by JoannaBlatt** [SeraphinaStephen/tomato-root-architecture#19]
Find out how to create a timer that will run a script after 30 minutes.

Probably will want to use Javascript. This will automatically delete files.

**Comment by JoannaBlatt** [comment]
Will use browser cookies for session id purposes, so look at that.

**Comment by SeraphinaStephen** [comment]
Looking into how to implement, the timer, cookies, and pop up boxes.

**Comment by SeraphinaStephen** [comment]
https://www.w3schools.com/jsref/met_win_settimeout.asp

Still reading up on this topic, this resource I was reading earlier this week seems like what I need.

**Comment by SeraphinaStephen** [comment]
I wasn't able to update this last night since I had left for work earlier then expected, but I intend to start coding a timeout script

**Comment by SeraphinaStephen** [comment]
Starting a new file in the github for this script

**Comment by SeraphinaStephen** [comment]
I am still working on this

**Comment by SeraphinaStephen** [comment]
I am still working on this same topic, I am just working out how to properly add what I need without making a mess of the code

**Comment by SeraphinaStephen** [comment]
Still updating the javascript, I've added a timer that should be set to 30 minutes and when that amount of time passes an alert window will pop up

**Comment by SeraphinaStephen** [comment]
I just uploaded what I had so far for the timeout javascript, I will continue to work on it after I am back from work

**Comment by JoannaBlatt** [comment]
I'm not seeing this commit.

**Comment by SeraphinaStephen** [comment]
I just got home from work, I'm going to try and work on this timer again while making dinner

**Comment by SeraphinaStephen** [comment]
I am actually feeling very sick, I won't be able to do much more than I already have tonight

**Comment by ZekkieMcCormick** [comment]
Is being worked in under 'track user session,' don't think a timer is going to be used anymore.
