### ISSUE TITLE
Wireframe and Prototype

### ISSUE THREAD

**Issue by ZekkieMcCormick** [SeraphinaStephen/tomato-root-architecture#2]
Finish wireframe and prototype in Figma

**Comment by ZekkieMcCormick** [comment]
Wireframe complete https://www.figma.com/proto/rJUKd3ygfg4gtYPeAYGYYw/WIREFRAME?node-id=2-2&starting-point-node-id=2%3A2&mode=design&t=Ik5Lnm0LLx1UEaY4-1

**Comment by ZekkieMcCormick** [comment]
Prototype (the animations on the wireframe) complete, need to implement Magda's comments now

**Comment by ZekkieMcCormick** [comment]
it would be good to have a button to download the underlying numeric data for the Pareto Front
It would be awesome to be able to upload multiple plants at the same time - and scroll through the observed RSA vs. calculated Pareto Front solutions - so some kind of drop-down selection menu based on the PlantID / RootID would be good (in the example input data - that would be in IMAGE column.
Not sure if we would necessarily would like to have a log-in and account - as this would require us to store people's data somewhere (on the server). It would be easier to have upload-and-play rather than user-specific stuff. 
From my own experience - it would be good to have multiple tabs - such as Data Upload // Pareto Front Visualization // Data Analysis // and have download buttons for each section - if you'd like to download specific image/graph then you can do that. But also if you d like to download the entire underlying dataset - that would be kick ass too.
-Magda's comments to be implemented

**Comment by SeraphinaStephen** [comment]
I am working on the (Upload page) wireframe

**Comment by ZekkieMcCormick** [comment]
Altered home tab to Magda's liking, working on about now

**Comment by ZekkieMcCormick** [comment]
About page altered, fixing prototype now

**Comment by ZekkieMcCormick** [comment]
Prototype fixed, original and new version functioning. Waiting on @SeraphinaStephen to finish upload wireframe to include in prototype.

**Comment by ZekkieMcCormick** [comment]
Made QOL (quality of life) changes to prototype, separated original prototype (including login, profile, etc) from new one in document (used to bounce between the two in prototype mode).

**Comment by SeraphinaStephen** [comment]
Continuing to work on the upload screen wire frame, added a placeholder for a options dropdown, and learning how to properly use figma.

**Comment by SeraphinaStephen** [comment]
Updated The upload screen to resemble something more complete, I am going to refer to the research paper to check over if what I have so far meets the expectations.

**Comment by ZekkieMcCormick** [comment]
Fixed Figma team issues (We were on wrong Figma, found issue, migrated, and sent correct link to team).

**Comment by SeraphinaStephen** [comment]
I've looked into a couple of website hosting options as considerations, these all seem pretty well reviewed so going forward I'll look into if that fit for what we need.

These where recommended as beginner friendly:  

https://www.a2hosting.com/web-hosting/?aid=5c9400b326496&cid=11111111&chan=code2

https://www.dreamhost.com/hosting/

These where recommended also and have a deal for cheaper hosting:  

https://www.nixihost.com/hosting/reddit

https://www.knownhost.com/reddit

**Comment by SeraphinaStephen** [comment]
Looking over the requirements for the wireframe from Magda just to re-access what I still need to be finishing up, I also added an email communication that I don't believe was in the google drive yet to the folder as a PDF

**Comment by SeraphinaStephen** [comment]
I've created a bulleted list for requirements for the part of the wireframe I'm working on and going forward I'm either going to be researching and / or implementing the bullet points

**Comment by SeraphinaStephen** [comment]
Added A new screen for the drop down menu and, a new screen for uploading multiple plants at the same time. I will want to ask for advice later on

**Comment by SeraphinaStephen** [comment]
Altering the upload screen on figma, hoping to have a more complete version very soon

**Comment by SeraphinaStephen** [comment]
I will need to leave for work, but I have checked off all of the immediate boxes for what the upload wire frame will need, going forward I want to ask Joanna about the code and what Zekkie thinks of the overall design. 

I will be moving on to drafting my email for the website domain later tonight after I return from work.

**Comment by SeraphinaStephen** [comment]
Started working on finishing up wirefarme for upload screen

**Comment by SeraphinaStephen** [comment]
I completely changed what I had previously for the upload wireframe to something that I think is much more in line with what was requested by Magdalena however I am still curious as to what she meant by:

It would be awesome to be able to upload multiple plants at the same time - and scroll through the observed RSA vs. calculated Pareto Front solutions - so some kind of drop-down selection menu based on the PlantID / RootID would be good (in the example input data - that would be in IMAGE column.

I don't know if we need a scrolling selection for the RSA vs Calculated pareto Front solutions and a dropdown for the PlantID and RootID or if both of those are one in the same

**Comment by SeraphinaStephen** [comment]
I reviewed the requested inclusions and made sure that those where expressed on my part of the wire frame so its clear to anyone looking over it, I will work on adding extra separate notes on what everything is when I start working again which will not take very long 

I would like to ask Zekkie what they think about the upload screen and if I'm missing anything obvious but as its getting late I will stop here for the night.

**Comment by SeraphinaStephen** [comment]
I'm going to try and finish up everything i need for the wireframe in the next 30 mins.

**Comment by SeraphinaStephen** [comment]
After I get a response on the questions I had on the wireframe, I actually wanted to ask questions on the parts of what was asked for to be included on the user upload screen,

I believe those questions would come with feedback on the user upload screen however.

**Comment by SeraphinaStephen** [comment]
I was looking at one of the examples provided by Magda (https://plantmodelling.shinyapps.io/shinyRootBox/) 
and I was wondering if we are going to need any sliders/number inputs, or if we're only taking a file as input, I did use this exaple to translate what Magda said she wanted into the wireframe.
