### ISSUE TITLE
Poster

### ISSUE THREAD

**Issue by ZekkieMcCormick** [SeraphinaStephen/tomato-root-architecture#24]
Starting

**Comment by ZekkieMcCormick** [comment]
Working in Figma

**Comment by ZekkieMcCormick** [comment]
Still working

**Comment by ZekkieMcCormick** [comment]
Almost done, will just need text touchups from Joanna

**Comment by ZekkieMcCormick** [comment]
Starting again

**Comment by ZekkieMcCormick** [comment]
Poster complete

**Comment by JoannaBlatt** [comment]
Can you put the link to the poster somewhere? I can look over it once you do.
