### ISSUE TITLE
'Sample' Button Functionality

### ISSUE THREAD

**Issue by ZekkieMcCormick** [SeraphinaStephen/tomato-root-architecture#29]

**Comment by JoannaBlatt** [comment]
should just add the sample output to /home/dh_an3skk/arjun-chandrasekhar-teaching.com/tomato/sample/results
then just pass this file to the javascript
to call sample:
```
<?php
if exists($_POST["sampleResults"]) {
    pass sample path
}
else {
   pass
}
```

or something like this
I'm not sure if it's in post but testing any of the places it could be would reveal it. Basically, pass variable saying use sample, then use hard coded sample results path.

**Comment by ZekkieMcCormick** [comment]
Starting

**Comment by ZekkieMcCormick** [comment]
Fixed missized buttons and uploaded sample file to server

**Comment by ZekkieMcCormick** [comment]
Might need to create new php file for this

**Comment by ZekkieMcCormick** [comment]
Still on this

**Comment by ZekkieMcCormick** [comment]
I was overcomplicating things, I just made a special php page for the sample case and redirect there. Working on making buttons match again

**Comment by ZekkieMcCormick** [comment]
Made separate button issue. All buttons are busted HTML wise, but are able to be worked on rn.
