### ISSUE TITLE
Tentative Timeline

### ISSUE THREAD

**Issue by ZekkieMcCormick** [SeraphinaStephen/tomato-root-architecture#3]

**Comment by ZekkieMcCormick** [comment]
Google sheet created with class dates and calendar

**Comment by ZekkieMcCormick** [comment]
Finished adding dates and front end goals, waiting on @JoannaBlatt to add back end goals now (https://docs.google.com/spreadsheets/d/1UOWbuTC_X4prha0wsEarNuqZjH_w5MnHCCTsyiBO6nI/edit?usp=sharing)

**Comment by JoannaBlatt** [comment]
Added some backend goals

Tentative timeline complete
