### ISSUE TITLE
Home Page Code

### ISSUE THREAD

**Issue by ZekkieMcCormick** [SeraphinaStephen/tomato-root-architecture#5]

**Comment by ZekkieMcCormick** [comment]
Setup new markdown language IDE (WYSIWYG, Blue Griffon is what I used to use, trying Apache Netbeans because Blue Griffon is horribly buggy). Will push first files onto server after discussion Monday.

**Comment by ZekkieMcCormick** [comment]
Refreshed knowledge of html and css, working on starter files now

**Comment by ZekkieMcCormick** [comment]
Switched to VS Code, netbeans was not cutting it :( Maybe I'll try another WYSIWYG editor later but for now good ole code will do

**Comment by ZekkieMcCormick** [comment]
Starting

**Comment by ZekkieMcCormick** [comment]
I didn't realize these only appeared at the time I pushed, not at the time that I committed. The commit time stamps are the correct ones. (1hr and 30 minutes ago respectively). I have been trying to get the image placed correctly.

**Comment by ZekkieMcCormick** [comment]
Forgot to reference issue, but commit 30 minutes ago "Almost there with image, created table, still figuring out justifications so that it's all centered"

**Comment by ZekkieMcCormick** [comment]
Still working on image placement, it really doesn't want to come together

**Comment by ZekkieMcCormick** [comment]
Starting again

**Comment by ZekkieMcCormick** [comment]
Starting

**Comment by ZekkieMcCormick** [comment]
Reviewed WPengine, as suggested by Magda's IT. It requires WordPress to be used. I have attempted this in the past, but reviewed a second time if it is possible to use the files I've created on WP. It is very very difficult to. Am going to look into the other suggestion, A2 Hosting. Will get back to Magda by EOD.

**Comment by ZekkieMcCormick** [comment]
A2 Hosting will work, but for maintenance reasons it would be ideal to get Dr. C's already working personal website working for ours as well. Will switch to begin working on page flexing, but will probably attempt SSH/digging around on that later.

**Comment by ZekkieMcCormick** [comment]
Not committing because it's broken right now (lol) but I'm doing flexbox on the home page so it flexes appropriately to smaller screen sizes (https://css-tricks.com/snippets/css/a-guide-to-flexbox/). I'm doing it in such a way that other pages should inherit these properties and don't need individual code (or, in the least, much of it).

**Comment by ZekkieMcCormick** [comment]
![Screenshot 2024-02-24 at 10-16-25 Tomato Root Architecture](https://github.com/SeraphinaStephen/tomato-root-architecture/assets/143543498/b182a941-fd3c-412c-8b1d-f80afbe53b17)
Still messed up, but it's flexing. The issue is that there is one div and one table, the table doesn't want to flex to the entirety of the div so I think I need to either move the flexing to either the rows of the table or to the outer div and situate that div better in the CSS.

**Comment by ZekkieMcCormick** [comment]
Starting

**Comment by ZekkieMcCormick** [comment]
attempted SSH via OpenSSH on my Linux machine, was unsuccessful but everything is properly set up to SSH when I figure it out. I send a message to Dr. C to meet with him to work on it.

**Comment by ZekkieMcCormick** [comment]
Issue with flexing is due to 'real' images not being uploaded. Works with sample images now. Also had to move flex command to outer containing div. Worked on other spacing as well.

**Comment by ZekkieMcCormick** [comment]
Made a commit 25 mins ago, forgot to add #5-- Added file verification so only CSV files may be uploaded

**Comment by JoannaBlatt** [comment]
footer overlaps upload button on edge browser

**Comment by ZekkieMcCormick** [comment]
Went through files to grab good sample images to display on home page

**Comment by ZekkieMcCormick** [comment]
Images won't display properly-- Working on it

**Comment by ZekkieMcCormick** [comment]
Had to convert the PDFs to JPGs lol, working now

**Comment by ZekkieMcCormick** [comment]
Working on changing pylab graph colors to match color scheme

**Comment by ZekkieMcCormick** [comment]
Still working on this- Helpful reading/understanding pylab in context.

**Comment by ZekkieMcCormick** [comment]
Starting again, going to switch from pylab to fixing chrome issues as Joanna has issues on chrome

**Comment by ZekkieMcCormick** [comment]
Fixed the footer!

**Comment by ZekkieMcCormick** [comment]
Starting

**Comment by ZekkieMcCormick** [comment]
Long discussion with Joanna about whether to continue with session ID or to try to use JS on front end. Decided to try JS on front end. Currently working on changing button to be form used in 'form testing' on server side, so that it becomes functional.

**Comment by ZekkieMcCormick** [comment]
Besides the form for the sample button to add functionality to it, the home page is complete. I will close this issue and create a new one for that, as that is an issue less related to home HTML and more related to PHP/Scripting.
