### ISSUE TITLE
Create output data (image and other tangential data)

### ISSUE THREAD

**Issue by ZekkieMcCormick** [SeraphinaStephen/tomato-root-architecture#8]

**Comment by JoannaBlatt** [comment]
Watching a video about incorporating python into websites.

**Comment by JoannaBlatt** [comment]
Looking into interfacing. Will probably also work on other stuff shortly.

**Comment by JoannaBlatt** [comment]
Created automated pipeline file and working on testing

**Comment by JoannaBlatt** [comment]
Pipeline works on my system. Will create setup file for others first, then have them test it. It should be ready to setup and integrate with the website after.

**Comment by JoannaBlatt** [comment]
Somehow lost oryx build text file so working on figuring that out

**Comment by JoannaBlatt** [comment]
At this point I think the automated pipeline is ready to be tested by someone else. First with proper input. If that works I'll work on handling improper input and integration. Or just check integration with the website.

**Comment by JoannaBlatt** [comment]
It currently creates all output files needed from the input file given.

**Comment by JoannaBlatt** [comment]
I have emailed Dr. C about the pareto front looking different than the expected image.

**Comment by JoannaBlatt** [comment]
Dr. C replied saying it was incorrect so I'm looking into this now.

**Comment by JoannaBlatt** [comment]
Rerunning the large file. Gave Dr. C my automated pipeline file and all resulting files from running the input file I was given.

**Comment by JoannaBlatt** [comment]
Still looking into this. Trying to see if I can find anything from what it was suggested I look into. Will look into further later.
